### ISSUE TITLE
Too many tabs in output on Windows

### ISSUE THREAD

**Issue by Welding-Torch** [szktkfm/mdtt#6]
When I use `mdtt` on Windows, enter some text, and then quit- the output has too many tabs (for some reason).
![image](https://github.com/szktkfm/mdtt/assets/46340124/46ee2dda-1106-4d08-ab47-053b4f1342c3)
This is on cmd.

**Comment by szktkfm** [comment]
It seems that the difference between LF and CRLF line endings might be related to this issue. I'll fix it!

**Comment by Welding-Torch** [comment]
Confirmed, it is fixed. Thank you!
